spring.application.name=taco-cloud
server.port=8085
spring.thymeleaf.cache=false

spring.mongodb.uri=mongodb+srv://ytj12132:${taco123}@cluster0.brtt8gz.mongodb.net/tacocloud?retryWrites=true&w=majority