spring.application.name=taco-cloud

server.port=8085

spring.thymeleaf.cache=false

spring.data.mongodb.auto-index-creation=true

spring.data.mongodb.uri=mongodb+srv://ytj12132:${taco1234}@cluster0.brtt8gz.mongodb.net/tacocloud?retryWrites=true&w=majority